import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger} from "@/components/ui/dropdown-menu";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

const languages = [
  {code: 'ko', label: '한국어'},
  {code: 'en', label: '영어'},
  {code: 'zh', label: '중국어'},
  {code: 'ja', label: '일본어'},
  {code: 'fr', label: '프랑스어'},
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="absolute top-2 right-2">
        <DropdownMenu>
          <DropdownMenuTrigger>
            🌐
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            {languages.map(lang => (
              <DropdownMenuItem key={lang.code}>{lang.label}</DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
        {children}
      </body>
    </html>
  );
}

